### ISSUE TITLE
Maximum score not on results page

### ISSUE THREAD

**Issue by derpadoo** [CybercentreCanada/assemblyline4_docs#28]
First off, love Assemblyline so far!

As for the issue, the documentation says the maximum score should be present for a submission, but it isn't.  Is the maximum score supposed to be the "max_score" key/value returned from the API?  It would be nice if that was surfaced through the GUI.  I may be missing it, but I can't find how to view the max score for a submission outside of the API (if that's a separate ticket, let me know).

1) Screenshot from https://cybercentrecanada.github.io/assemblyline4_docs/en/user_manual/results/

![image](https://user-images.githubusercontent.com/27816854/145052907-30ed8a5d-3733-41ab-84bb-440135f66350.png)

2) Code line: https://github.com/CybercentreCanada/assemblyline4_docs/blob/cc9d49c9a9871528adcc3b61614bcb8f9b65cd38/docs/user_manual/results.md?plain=1#L55

**Comment by cccs-rs** [comment]
Hello!

So I suppose we should add to our docs: in order to reveal the actual score of the submission, you would need to hover over the verdict (in the case of the screenshot, 'Malicious').

Similarly if you hover over the 'Verdict' in the Submission Details, that will also reveal the submission's score.

We'll make changes to the documentation accordingly! 😀

**Comment by cccs-rs** [comment]
https://github.com/CybercentreCanada/assemblyline4_docs/commit/67c688165e5a1a3c1a66ad93464f3a016efb9a97

**Comment by derpadoo** [comment]
Ah, there it is!  Thanks for clarifying.  If I wanted to submit a suggestion to move the max score to a visible table column, which one of these sub-repos would be best?

https://github.com/CybercentreCanada/assemblyline-ui

https://github.com/CybercentreCanada/assemblyline-ui-frontend

**Comment by cccs-rs** [comment]
Well if you want, you can submit it to one of our channels in our Discord community in case there are more things to revamp in the frontend! (https://discord.gg/GUAy9wErNu) 

Otherwise, ui-frontend I think would be the best place to suggest that.
